module.exports = {
  getMazeState: {
    pony: [121],
    domokun: [218],
    'end-point': [62],
    size: [15, 15],
    difficulty: 0,
    data: [
      ['west', 'north'],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['west', 'north'],
      ['north'],
      ['west', 'north'],
      ['north'],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['north'],
      ['west'],
      [],
      ['west', 'north'],
      [],
      ['west'],
      ['north'],
      ['west'],
      [],
      ['west'],
      ['west'],
      ['north'],
      [],
      ['north'],
      ['north'],
      ['west'],
      ['west', 'north'],
      ['north'],
      ['west'],
      ['north'],
      ['west', 'north'],
      [],
      ['west', 'north'],
      ['north'],
      ['west'],
      ['north'],
      ['north'],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['west'],
      ['west'],
      ['north'],
      ['north'],
      ['west'],
      ['west'],
      ['west', 'north'],
      ['west'],
      ['north'],
      ['north'],
      ['north'],
      ['west'],
      ['west'],
      ['west', 'north'],
      ['west'],
      [],
      ['west', 'north'],
      [],
      ['west'],
      ['west'],
      [],
      ['west'],
      [],
      ['west'],
      ['west', 'north'],
      ['west'],
      ['west'],
      [],
      ['west'],
      ['north'],
      ['west'],
      ['west'],
      ['west', 'north'],
      [],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['north'],
      [],
      ['west'],
      [],
      ['west', 'north'],
      ['north'],
      ['west'],
      ['west'],
      [],
      ['west'],
      ['north'],
      ['west'],
      ['north'],
      [],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['west'],
      ['north'],
      ['west'],
      ['west'],
      ['west'],
      ['west', 'north'],
      ['north'],
      ['west', 'north'],
      [],
      ['west', 'north'],
      ['north'],
      ['north'],
      [],
      ['north'],
      ['west'],
      [],
      ['west', 'north'],
      [],
      ['west'],
      ['west'],
      ['west'],
      ['west'],
      ['west'],
      ['north'],
      ['north'],
      ['west'],
      ['west', 'north'],
      ['north'],
      ['west'],
      ['north'],
      ['west', 'north'],
      [],
      ['west', 'north'],
      ['west'],
      ['west'],
      ['north'],
      ['west'],
      ['west'],
      ['north'],
      ['west'],
      ['west'],
      ['west'],
      ['west'],
      ['north'],
      ['north'],
      [],
      ['west', 'north'],
      [],
      ['west'],
      ['north'],
      ['west'],
      [],
      ['west', 'north'],
      [],
      ['west'],
      ['north'],
      ['west'],
      ['west', 'north'],
      ['north'],
      ['north'],
      ['west', 'north'],
      [],
      ['west'],
      ['north'],
      ['west'],
      ['north'],
      [],
      ['west'],
      ['west', 'north'],
      ['north'],
      ['west'],
      ['west'],
      ['west'],
      ['west', 'north'],
      [],
      ['north'],
      ['north'],
      ['west', 'north'],
      [],
      ['north'],
      ['north'],
      ['west', 'north'],
      ['west'],
      [],
      ['west', 'north'],
      [],
      ['west'],
      ['west'],
      ['north'],
      ['north'],
      ['west', 'north'],
      ['west'],
      ['west'],
      ['west', 'north'],
      ['north'],
      ['west'],
      [],
      ['west', 'north'],
      ['west'],
      ['west'],
      ['west'],
      ['west'],
      ['north'],
      ['west', 'north'],
      [],
      ['west'],
      [],
      ['west'],
      ['north'],
      ['west'],
      ['north'],
      ['west'],
      ['west'],
      [],
      ['west'],
      ['north'],
      ['north'],
      [],
      [],
      ['west', 'north'],
      [],
      ['north'],
      ['north'],
      [],
      ['west'],
      ['west'],
      [],
    ],
    maze_id: 'f7de9fc3-eb4a-42e1-ade4-5bfdff315a62',
    'game-state': {
      state: 'Active',
      'state-result': 'Successfully created',
    },
  },
};
